# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a1415731860a224eb82d7dd59ac2b84602daadfddcadfc52e24a7867354eb2f06f857e7e54d93880bae1dfeb9d83f9520df8a5fd3d5085a5d5edd3157f2382

test:
  secret_key_base: 1bec280c7ea017c5f43e4a529867a612df0b7af81a249bc26c189c247723617f822febaed637fdf3c870a84d030cae46b81141302bb673b90a494ca545e9b525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
